### ISSUE TITLE
JSON support for gRPC-Web transport

### ISSUE THREAD

**Issue by akshayjshah** [bufbuild/connect-es#265]
**Is your feature request related to a problem? Please describe.**

Using the gRPC-Web transport locks me into using binary Protobuf serialization, which makes the network inspector fully useless.

**Describe the solution you'd like**

I'd like the gRPC-Web transport to support JSON serialization, like the Connect transport. This would make the network inspector only partially useless :)

**Describe alternatives you've considered**

I could switch to the Connect protocol, but this is a more invasive change. Why not support the same switch in both protocols?

**Additional context**

Originally brought up by @tannerlinsley in Slack.

**Comment by fubhy** [comment]
Regarding the point about the network inspector, it'd be possible to build a browser extension for that :-).

**Comment by akshayjshah** [comment]
> Regarding the point about the network inspector, it'd be possible to build a browser extension for that :-).

Definitely possible, but difficult to do in a way that's universally usable. Converting binary protobuf to JSON requires the schema, and there's no standard for fetching a schema. (That's what Buf is building!) The gRPC reflection protocol is sort of close, but it requires bidirectional streaming....which isn't feasible from browsers.

In short, where would the browser extension get the schema from?

**Comment by derekperkins** [comment]
https://github.com/bufbuild/protobuf-es claims to support the canonical json format, so I assume it's already being generated with access to the schema. This issue is just to wire up the option, is that right?

**Comment by akshayjshah** [comment]
> https://github.com/bufbuild/protobuf-es claims to support the canonical json format, so I assume it's already being generated with access to the schema. This issue is just to wire up the option, is that right?

That's correct!

**Comment by timostamm** [comment]
There is a browser extension for the official gRPC-web client: [grpc-web-devtools](https://github.com/SafetyCulture/grpc-web-devtools). 

It works by adding an interceptor to the the client, and sending payloads to the extension, which renders it in a dedicated inspector tab.

There are a few downsides with this approach:
- Users need to install the extension.
- The web application needs to opt in, passing a client object to a function provided by the extension.
- The extension will not show the actual network traffic, only what is visible in user land. That means you don't see headers hidden because of CORS, and have to correlate failed requests with requests in the network inspector.

For those reasons, I believe that using JSON on the wire provides a better UX than an extension, but I don't want to disregard use cases where the Connect protocol isn't an option. I think the best way forward here is to look into gRPC-web + JSON before we look into browser extensions.

**Comment by timostamm** [comment]
Just a quick update: We've added support for the JSON format to the gRPC-web transport a while back. It will be released in the first version that ships with the new shared package `@bufbuild/connect-core`, as described in the [road map here](https://github.com/bufbuild/connect-web/discussions/315).

**Comment by tannerlinsley** [comment]
Just checkin in on the progress here as v1 seems to have landed. Is this possible in the latest release? We are also investigating switching our backend to use the connect protocol if this isn't ready yet.

**Comment by smaye81** [comment]
The connect-web package that uses `connect-core` is not yet published.  Only `connect-node` is using this right now.  We hope to have `connect-web` updated within the next couple weeks.

**Comment by timostamm** [comment]
Support for JSON in the gRPC-web transport is finally available with [v0.8.0](https://github.com/bufbuild/connect-es/releases/tag/v0.8.0) and can be enabled with a boolean option:

```diff
const transport = createConnectTransport({
  baseUrl: "https://demo.connect.build",
+ useBinaryFormat: false,
});
```

**Comment by unicomp23** [comment]
I'm using caddy as a reverse proxy, and getting this error.  Should I be overriding the content-type of the response to something?

[invalid_argument] unexpected response content type "text/html; charset=utf-8"
    at validateResponse (validate-response.js:46:1)
    at connect-transport.js:61:74
    at async Object.unary (connect-transport.js:45:1)
    at async Object.upsert (promise-client.js:66:1)
    at async DefaultSceneWithTexture.createScene (defaultWithTexture.ts:136:13)
    at async babylonInit (index.ts:38:19)

**Comment by unicomp23** [comment]
@timostamm ^this is happening in the browser
