### ISSUE TITLE
Add bidirectional stream support 

### ISSUE THREAD

**Issue by euskadi31** [bufbuild/connect-es#419]
**Is your feature request related to a problem? Please describe.**

Using bidirectional stream.

**Describe the solution you'd like**

I think you could use the Websocket to be able to support this feature

**Describe alternatives you've considered**

See: https://github.com/bufbuild/connect-web/issues/416

**Comment by timostamm** [comment]
Axel, the idea is that one simple protocol should be good enough for all clients. We decided against WebSockets because they would add much complexity to the very simple [Connect protocol](https://connect.build/docs/protocol). Note that there has been some movement with browser support for better streaming support, for example [in Chrome](https://developer.chrome.com/articles/fetch-streaming-requests/), and with the [WebTransport API](https://developer.mozilla.org/en-US/docs/Web/API/WebTransport_API).

For select use cases you need _now_, it should be very feasible to implement a [client Transport](https://github.com/bufbuild/connect-es/blob/89d021dc1285d5358876460a8fa3bc54157822f9/packages/connect/src/transport.ts#L29) that uses WebSockets under the hood, and to add a WebSocket route on the server that calls the service implementation. It's definitely not a turn-key solution, but streaming rarely is, and you can still benefit from the protobuf schema.

For those reasons, we currently do not plan to support bidi streaming via WebSockets.
