### ISSUE TITLE
Compression for grpc-web

### ISSUE THREAD

**Issue by mehdipourfar** [bufbuild/connect-es#625]
I use connectweb for my frontend application. My backend has a [grpc-web](https://github.com/improbable-eng/grpc-web) proxy and I use grpc-web protocol for connectweb client. Everything works fine except compression. If I set header `grpc-encoding: gzip`, my server returns a lightweight response but I get parse error from connectweb. Is there any way to fix it? Can I contribute in a way?

**Comment by timostamm** [comment]
Hey Mehdi, because browsers always send an `Accept-Encoding` header, the situation is a bit muddy. https://github.com/bufbuild/connect-es/issues/230#issuecomment-1211787444 has a bit more context and details.

Especially for unary RPCs, full-body compression works quite nicely, and is handled transparently by the browser. Perhaps it is possible to enable it for gRPC-web requests in the improbably proxy?

**Comment by mehdipourfar** [comment]
Thanks for your response. I've added a gzip middleware to my server and now it works quite well:)
