### ISSUE TITLE
`package-lock.json` missing `resolved` & `integrity` fields

### ISSUE THREAD

**Issue by felschr** [bufbuild/connect-es#719]
Hi, while trying to package `protoc-gen-connect-es` for nixpkgs, I've ran into the issue that the `package-lock.json` doesn't contain any `resolved` & `integrity` fields since https://github.com/bufbuild/connect-es/commit/411bba56a53310dd510c1a0bbd65629b7141b4f5: https://github.com/NixOS/nixpkgs/pull/243432#issuecomment-1635737984
These fieldd should exist according to the docs: https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json

This can likely be fixed by regenerating the lock file from scratch and/or updating to newer versions of npm.

I've also found the same issue with protobuf-es: https://github.com/bufbuild/protobuf-es/issues/526

**Comment by timostamm** [comment]
@felschr, I'm not entirely sure what commands @smaye81 ran, but my guess is that the fields were removed from the lock 
file by re-generating it.

If you run the following commands:

```bash
$ npm --version            
9.8.0
$ rm -rf package-lock.json 
$ npm install
```

The lock-file is re-created, and all `resolved` and `integrity` fields are removed from the lock file. In this case, we removed a package from the repository, and the alternative to the commands above would be to edit the lock file manually, or to delete the node_modules directory as well before running `npm install`. The latter will also bump versions within the defined constraints.

I think it might not be completely uncommon to have lock files without those fields in the wild because of this behavior of npm...

Do you know an alternative in situations like this that retains the fields?

**Comment by smaye81** [comment]
Just to confirm -- I used npm version `9.5.0` when regenerating the lock file.

**Comment by lilyinstarlight** [comment]
Regenerating the lockfile should be adding those fields, not removing them. I just confirmed that locally with npm 9.7.2 removing the lockfile and doing `npm install` adds those fields correctly

Can you share the output of `npm config list` so we can check if you have some local setting that is causing that?

**Comment by lilyinstarlight** [comment]
Oh there's an upstream issue for it. You might have to remove both `node_modules` and `package-lock.json` to get it to correctly regenerate. See https://github.com/npm/cli/issues/6301

**Comment by smaye81** [comment]
I just created https://github.com/bufbuild/connect-es/pull/720 to regenerate package-lock.json using the instructions in https://github.com/npm/cli/issues/6301. Let me know if this is what is needed to satisfy the nixpkgs issue.

Also please note that we can't guarantee this won't happen again due to the open npm cli issue. We aren't committing to manually ensuring the lock file always has these properties. Hopefully the issue on the npm side is resolved soon.

**Comment by smaye81** [comment]
Also related fix in Protobuf-ES:  https://github.com/bufbuild/protobuf-es/pull/527

**Comment by felschr** [comment]
@smaye81 Thank you for the quick fix and the new release of `protobuf-es`!

**Comment by felschr** [comment]
npm issues that track the problem of missing `integrity` & `resolved` fields:
https://github.com/npm/cli/issues/4263, https://github.com/npm/cli/issues/4460 https://github.com/npm/cli/issues/6301

Issue on `protobuf-es` to track this issue and hopefully find a long-term solution:
https://github.com/bufbuild/protobuf-es/issues/589
